<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\wordshu.txt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\wordshu.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WordGame.Persistence\WordGame.Persistence.csproj" />
  </ItemGroup>

</Project>
