
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.Maui.Controls" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.Maui.Controls.Compatibility" Version="10.0.11" />
  </ItemGroup>
</Project>
